DORIS_DB: tmp:tmp@111@tcp(172.16.3.23:9030)/dmp_query
OUTPUT_DIR: /Users/chemanyu/monitor
MYSQL_DB: dmp:9Jd7TA5yw5Il3cI@tcp(172.16.3.25:3306)/dmp
MYSQL_ADN_DB: dmp:9Jd7TA5yw5Il3cI@tcp(172.16.3.25:3306)/adn
REDIS_POOL_DB: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
REDIS_POOL_DB_CRC: 127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004,127.0.0.1:8005,127.0.0.1:8006
SERVER_PORT: 8000